<?php require_once 'templates/layout/header.phtml'; ?>

<?php
?>


<div class="container mt-5">
    <h2 class="text-center">Agregar Categorías</h2>
    <form action="addcategorias" method="POST">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" required>
        </div>

        <div class="form-group">
            <label for="genero">Género</label>
            <input type="text" class="form-control" name="genero" id="genero" required>
        </div>

        <div class="form-group">
            <label for="temporada">Temporada</label>
            <input type="text" class="form-control" name="temporada" id="temporada" required>
        </div>

        <div class="form-group">
            <label for="marca">Marca</label>
            <input type="text" class="form-control" name="marca" id="marca" required>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Enviar</button>
    </form>
</div>



<?php require_once 'templates/layout/footer.phtml'; ?>