<?php require_once 'templates/layout/header.phtml'; ?>

<?php
?>


<div class="container mt-5">
    <h2 class="text-center">Agregar Categorías</h2>
    <form action="addcategorias" method="POST">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" required>
        </div>

        <div class="form-group">
            <label for="genero">Género</label>
            <input type="text" class="form-control" name="genero" id="genero" required>
        </div>

        <div class="form-group">
            <label for="temporada">Temporada</label>
            <input type="text" class="form-control" name="temporada" id="temporada" required>
        </div>

        <div class="form-group">
            <label for="marca">Marca</label>
            <input type="text" class="form-control" name="marca" id="marca" required>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Enviar</button>
    </form>
</div>


<h2>Lista de todas las categorias </h2>
<p>En la siguiente tabla se podra editar, o eliminar las categorias</p>



<div class="container mt-5">
        <h2 class="text-center">Tabla de Edicion</h2>
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">

        <tr>
            <th class="text-center">Nombre de la categoria</th>
        
            <th class="text-center">  Editar</th>
            <th class="text-center"> Borrar</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($categorias as $categoria): ?>
            <tr>
                <td class="text-center"> <?= $categoria->nombre ?></td>
            
                <td class="text-center">
                <a href="categoriaseditadas?id=<?= $categoria->ID_categoria ?>" class="btn btn-success">Editar</a>
        </td>
        <td class="text-center">
           <a href="" class="btn btn-danger">Borrar</a>
        </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<?php require_once 'templates/layout/footer.phtml'; ?>