<?php require_once 'templates/layout/header.phtml'; ?>
<form action="editarArticulo/<?= $prenda->ID_articulo ?>" method="POST" enctype="multipart/form-data">


    <div class="form-group">
        <label for="nombre">Nombre del artículo</label>
        <input type="text" class="form-control" id="nombre" name="nombre"
            value="<?= htmlspecialchars($prenda->nombre) ?>" required>
    </div>

    <div class="form-group">
        <label for="valor">Precio</label>
        <input type="text" class="form-control" id="valor" name="valor" value="<?= htmlspecialchars($prenda->valor) ?>"
            required>
    </div>

    <div class="form-group">
        <label for="descripcion">Descripcion</label>
        <input type="text" class="form-control" id="descripcion" name="descripcion"
            value="<?= htmlspecialchars($prenda->descripcion) ?>" required>
    </div>

    <div class="form-group">
        <label for="categoria">Categoría</label>
        <select class="form-control" name="categoria" id="categoria" required>
            <?php foreach ($categorias as $categoria): ?>
                <option value="<?= $categoria->ID_categoria ?>"><?= $categoria->nombre ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="imagen" enctype="multipart/form-data">Seleccione la nueva imagen.</label>
        <input type="file" class="form-control" name="imagen" id="imagen" accept="image/*" required>
    </div>

    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>

<?php require_once 'templates/layout/footer.phtml'; ?>