<?php require_once 'templates/layout/header.phtml';?>
<form action="editarArticulo/<?= $prenda->ID_articulo ?>" method="POST">


    <div class="form-group">
        <label for="nombre">Nombre del artículo</label>
        <input type="text" class="form-control" id="nombre" name="nombre" value="<?=$prenda->nombre ?>" required>
    </div>

    <div class="form-group">
        <label for="valor">Precio</label>
        <input type="text" class="form-control" id="valor" name="valor" value="<?=$prenda->valor ?>" required>
    </div>

    <div class="form-group">
        <label for="descripcion">Descripcion</label>
        <input type="text" class="form-control" id="descripcion" name="descripcion" value="<?=$prenda->descripcion ?>" required>
    </div>

    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>

<?php require_once 'templates/layout/footer.phtml'; ?>


