<?php require_once 'templates/layout/header.phtml' ?>

<?php //PREGUNTAR DONDE SE HACEN LAS VALIDACIONES 
?>

<ul class="list-group">
    <div class="container">
        <div class="row">
            <?php foreach ($prendas as $prenda): ?>
                <div class="col-md-6 mb-4">
                    <div class="row g-0 bg-body-secondary position-relative">
                        <div class="position-absolute top-50 start-50">
                        <img src="" class="img-thumbnail" alt="...">
                        </div>
                        <div class="col-md-6 p-4 ps-md-0">
                            <h5 class="mt-0"><?= $prenda->nombre ?></h5>
                            <p><?= $prenda->descripcion ?></p>
                            <div>$<?= $prenda->valor ?></div>
                            <p><a href="producto/<?= $prenda->ID_articulo ?>" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Ver</a></p>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> prendas</small></p>

<?php require_once 'templates/layout/footer.phtml' ?>