<?php require_once 'templates/layout/header.phtml' ?>

<?php //PREGUNTAR DONDE SE HACEN LAS VALIDACIONES 
?>

<ul class="list-group">
    <div class="container">
        <div class="row">
            <?php foreach ($prendas as $prenda): ?>
                <div class="col-md-6 mb-4">
                    <div class="row g-0 bg-body-secondary position-relative">
                        <div class="position-absolute top-50 start-50">
                            <img src="" class="img-thumbnail" alt="...">
                        </div>
                        <div class="col-md-6 p-4 ps-md-0">
                            <h5 class="mt-0"><?= $prenda->nombre ?></h5>
                            <p><?= $prenda->descripcion ?></p>
                            <div>$<?= $prenda->valor ?></div>
                            <p><a href="producto/<?= $prenda->ID_articulo ?>" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Ver</a></p>
                            <p>Categoria: <?= $prenda->categoria_nombre ?></p>
                            <a href="articuloseditados?id=<?= $prenda->ID_articulo ?>" class="btn btn-success">Editar</a>
                            <a href="eliminarArticulo/<?= $prenda->ID_articulo ?>" class="btn btn-danger">Borrar</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> prendas</small></p>

<h2>Administrar articulos</h2>
<div class="container mt-5">
    <h3 class="text-center">Agregar Articulos</h3>
    <form action="addarticulo" method="POST">

        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" required>
        </div>

        <div class="form-group">
            <label for="valor">Valor</label>
            <input type="number" class="form-control" name="valor" id="valor" required>
        </div>

        <div class="form-group">
            <label for="descripcion">Descripcion</label>
            <input type="text" class="form-control" name="descripcion" id="descripcion" required>
        </div>

        <div class="form-group">
            <label for="categoria">Categoría</label>
            <select class="form-control" name="categoria" id="categoria" required>
                <?php foreach ($prendas as $prenda): ?>
                    <option value="<?= $prenda->ID_categoria ?>"><?= $prenda->categoria_nombre ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Enviar</button>
    </form>
</div>



<?php require_once 'templates/layout/footer.phtml' ?>