<?php require_once 'templates/layout/header.phtml' ?>


<h1> <?= htmlspecialchars($prenda->nombre) ?> </h1>
<p> <?= htmlspecialchars($prenda->descripcion) ?> </p>
<p>$ <?= htmlspecialchars($prenda->valor)  ?></p>
<p>Categoria: <?= htmlspecialchars($prenda->categoria_nombre) ?> </p>

<?php
if ($prenda->Imagen != ''): ?>
    <img src="<?= htmlspecialchars($prenda->Imagen) ?>" class="imagenproductos" alt="Imagen de la categoría">
<?php else: ?>
    <p>No se encontró la imagen.</p>
<?php endif; ?>

<?php require_once 'templates/layout/footer.phtml' ?>